version: 2
updates:
  # Actualizar dependencias npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tuusuario"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Actualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "github-actions"
    commit-message:
      prefix: "ci"
